import { createHash } from 'node:crypto';
import { lstat, readFile, readdir, realpath } from 'node:fs/promises';
import path from 'node:path';

const MAX_FILE_BYTES = 256 * 1024;
const DENIED_NAME = /(?:transcript|history|prompt|(?:^|[-_.])env(?:ironment)?(?:$|[-_.])|credential|token|secret|settings?|permission|allowlist|trust|mcp|plugin|cron)/i;
const SECRET = /(?:\b(?:api[_-]?key|access[_-]?token|authorization|password|secret|private[_-]?key|cookie)\b\s*[:=]|https?:\/\/[^\s/]+[^\s]*[?&](?:token|api[_-]?key|key|secret|signature|sig|password|credential)=)/i;
const HOME_PATH = /(?:^|[\s"'`(])(?:\/Users\/[^/\s]+|\/home\/[^/\s]+|[A-Za-z]:\\Users\\[^\\\s]+)/;
const TILDE_RUNTIME_PATH = /~\/\.(?:claude|codex)(?:\/|\b)/i;
const GENERATED = /(?:generated by saddle|saddle-managed|saddle portable)/i;
const RUNTIME_CONFIG = /(?:^|\n)\s*(?:mcpServers\s*:|\[mcp_servers(?:\.|\])|permissions?\s*:\s*\{|(?:allowedTools|trustGrants)\s*:)/i;
const CONFIG_FIELD = /(?:^|\n)\s*(?:url|command|args)\s*[:=]/im;
const PORTABLE_DEV_SAFETY = `## Dev server safety

Never start a local development server unless the complete process tree is monitored and capped at 2048 MB RSS or less. A JavaScript heap limit alone is not sufficient because development tools can spawn workers and native processes outside the main runtime.

Before starting a development server, inspect the project's dev command and confirm that its wrapper monitors the full process group, terminates the group when it crosses the cap, and reports the reason. If the project has no suitable wrapper, stop and offer to install one before starting the server.

For Next.js projects, also confirm that the Turbopack root is explicit before starting development.
`;
const PORTABLE_MEMORY_PROTOCOL = `## Session continuity

At session start, read the current project dashboard and the most recent durable project notes before acting.

After a material change, append the decision, evidence, current state, and one concrete next action to the active durable note.

Before a context reset, compaction, branch, or handoff, save any chat-only artifacts, finalize the current checkpoint, and leave a resume pointer.

After a context reset, reload the dashboard, curated context, and latest durable note before continuing.

At session end, verify the work, make durable records internally consistent, and leave one concrete next action.
`;

const digest = (value) => createHash('sha256').update(value).digest('hex');
const stableId = (...parts) => `capture-${digest(parts.join('\0')).slice(0, 20)}`;
const slash = (value) => value.split(path.sep).join('/');

function advisory(text, heading = '') {
  const title = heading.toLowerCase();
  if (/(personal|human|health|family|location)/.test(title)) return { kind: 'personal-context', sensitivity: 'personal', reason: 'The section heading suggests personal context; this advisory classification requires explicit consent.' };
  if (/(server|dev safety|memory cap|hard rule|permission)/.test(title)) return { kind: 'operating-policy', sensitivity: 'standard', reason: 'The section heading suggests an operating policy; this is an advisory classification.' };
  if (/(model routing|subagents?|project|design|writing|de-?slop|voice|delivery orchestration|product conversations?|analytical discipline)/.test(title)) return { kind: 'project-standard', sensitivity: 'standard', reason: 'The section heading suggests a project-standard; this is an advisory classification.' };
  if (/(memory protocol|session continuity|session (?:start|end|checkpoint)|context (?:reset|before|after)|compact|resume|checkpoint|handover|durable notes?)/.test(title)) return { kind: 'session-continuity', sensitivity: 'standard', reason: 'The section heading suggests session continuity; this is an advisory classification.' };
  const sample = text.toLowerCase();
  if (/(personal|human|health|family|location)/.test(sample)) return { kind: 'personal-context', sensitivity: 'personal', reason: 'Personal-context terms were detected; this advisory classification requires explicit consent.' };
  if (/(\bclear\b|compact|resume|pre[- ]?context|post[- ]?context|checkpoint|handover|durable notes?|session (?:start|end)|context reset)/.test(sample)) return { kind: 'session-continuity', sensitivity: 'standard', reason: 'Explicit continuity or reset terms were detected; this is an advisory classification.' };
  if (/(server|dev safety|permission)/.test(sample)) return { kind: 'operating-policy', sensitivity: 'standard', reason: 'Operating-policy terms were detected; this is an advisory classification.' };
  if (/(model routing|subagents?|project|design|writing)/.test(sample)) return { kind: 'project-standard', sensitivity: 'standard', reason: 'Project-standard terms were detected; this is an advisory classification.' };
  return { kind: 'operating-policy', sensitivity: 'standard', reason: 'No stronger heuristic matched; this is an advisory operating-policy classification.' };
}

function denied(text, relative, heading = '') {
  if (GENERATED.test(text) || /(?:^|\/)saddle(?:[-_.]|\/|$)/i.test(relative)) return 'Generated Saddle material is not importable.';
  if (DENIED_NAME.test(relative)) return 'Runtime settings, history, credentials, trust, integration, or scheduled-task material is excluded.';
  if (RUNTIME_CONFIG.test(text) || (/\bmcp\b/i.test(heading) && CONFIG_FIELD.test(text))) return 'Runtime connection, permission, or trust configuration is excluded.';
  if (SECRET.test(text)) return 'Likely secret-bearing content is excluded.';
  if (HOME_PATH.test(text)) return 'Machine-specific absolute home paths cannot safely travel.';
  if (TILDE_RUNTIME_PATH.test(text)) return 'Source-runtime file references cannot travel unless Saddle has a portable replacement.';
  return null;
}

function utf8(buffer) {
  const text = new TextDecoder('utf-8', { fatal: true }).decode(buffer);
  if (text.includes('\0')) throw new Error('binary content');
  return text;
}

async function rootFor(runtimeRoot) {
  if (typeof runtimeRoot !== 'string' || !path.isAbsolute(runtimeRoot)) throw new TypeError('runtimeRoot must be an absolute caller-supplied path');
  return realpath(runtimeRoot);
}

async function regularUnder(root, relative) {
  const normalized = path.posix.normalize(relative.replaceAll('\\', '/'));
  if (!normalized || normalized === '.' || normalized.startsWith('../') || path.isAbsolute(normalized)) throw new Error('unsafe relative path');
  let current = root;
  for (const part of normalized.split('/')) {
    current = path.join(current, part);
    const info = await lstat(current);
    if (info.isSymbolicLink()) throw new Error('symlink traversal is not allowed');
  }
  const info = await lstat(current);
  if (!info.isFile()) throw new Error('not a regular file');
  const resolved = await realpath(current);
  if (!resolved.startsWith(`${root}${path.sep}`)) throw new Error('path escapes runtime root');
  return { relative: normalized, absolute: resolved, bytes: info.size };
}

function sections(text, lineOffset = 0) {
  const lines = text.split(/(?<=\n)/);
  const headings = [];
  let position = 0;
  for (let index = 0; index < lines.length; index += 1) {
    const match = /^##\s+(.+?)\s*#*\s*(?:\r?\n)?$/.exec(lines[index]);
    if (match) headings.push({ index, position, heading: match[1].trim() });
    position += Buffer.byteLength(lines[index]);
  }
  const chunks = [];
  const first = headings[0]?.index ?? lines.length;
  if (first > 0) chunks.push({ heading: undefined, startLine: lineOffset + 1, endLine: lineOffset + first, text: lines.slice(0, first).join('') });
  for (let i = 0; i < headings.length; i += 1) {
    const start = headings[i].index;
    const end = headings[i + 1]?.index ?? lines.length;
    chunks.push({ heading: headings[i].heading, startLine: lineOffset + start + 1, endLine: lineOffset + end, text: lines.slice(start, end).join('') });
  }
  return chunks.filter((chunk) => chunk.text.trim());
}

function authoredSections(text) {
  const lines = text.split(/(?<=\n)/);
  const ranges = managedLineRanges(text);
  const authored = [];
  let cursor = 1;
  for (const range of ranges) {
    if (cursor < range.start) {
      authored.push(...sections(lines.slice(cursor - 1, range.start - 1).join(''), cursor - 1));
    }
    cursor = range.end + 1;
  }
  if (cursor <= lines.length) authored.push(...sections(lines.slice(cursor - 1).join(''), cursor - 1));
  return authored;
}

function instructionCandidates(runtime, relative, text, forcedClassification) {
  return authoredSections(text).map((section) => {
    const classification = forcedClassification ?? advisory(section.text, section.heading);
    const portableTransform = /^memory protocol$/i.test((section.heading ?? '').trim()) &&
      (TILDE_RUNTIME_PATH.test(section.text) || HOME_PATH.test(section.text))
      ? 'memory-protocol-v1'
      : /dev(?:elopment)? server (?:safety|memory)|server safety/i.test(section.heading ?? '') &&
      (TILDE_RUNTIME_PATH.test(section.text) || HOME_PATH.test(section.text))
      ? 'dev-server-safety-v1'
      : undefined;
    const replacement = portableTransform === 'memory-protocol-v1' ? PORTABLE_MEMORY_PROTOCOL : portableTransform ? PORTABLE_DEV_SAFETY : section.text;
    const reason = denied(replacement, relative, section.heading);
    const transformReason = portableTransform === 'memory-protocol-v1'
      ? 'advisory classification: source-runtime memory roots and commands will be replaced with self-contained session-continuity procedures.'
      : portableTransform ? 'advisory classification: source-machine dev-safety references will be replaced with a self-contained 2 GB process-tree policy.' : classification.reason;
    return { id: stableId(runtime, 'instruction-section', relative, section.heading ?? 'introduction'), runtime, sourceType: 'instruction-section', source: relative, ...(section.heading ? { heading: section.heading } : {}), lineSpan: { start: section.startLine, end: section.endLine }, digest: digest(section.text), bytes: Buffer.byteLength(section.text), suggestedKind: classification.kind, suggestedSensitivity: classification.sensitivity, selectable: !reason, reasons: reason ? [reason] : [transformReason], ...(portableTransform ? { portableTransform } : {}) };
  });
}

function managedLineRanges(text) {
  const lines = text.split(/(?<=\n)/);
  const ranges = [];
  let start;
  for (let index = 0; index < lines.length; index += 1) {
    if (/<!--\s*saddle:managed:start\s+adapter=(?:claude|codex)\s*-->/.test(lines[index])) {
      start = start ?? index + 1;
    }
    if (start !== undefined && /<!--\s*saddle:managed:end\s+adapter=(?:claude|codex)\s*-->/.test(lines[index])) {
      ranges.push({ start, end: index + 1 });
      start = undefined;
    }
  }
  if (start !== undefined) ranges.push({ start, end: lines.length });
  return ranges;
}

async function assets(root, capabilityRelative, warnings) {
  const base = path.join(root, path.dirname(capabilityRelative));
  const found = [];
  async function walk(directory) {
    for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.')) continue;
      const absolute = path.join(directory, entry.name);
      const relative = slash(path.relative(root, absolute));
      if (entry.isSymbolicLink()) { warnings.push({ source: relative, reason: 'Symlinked capability asset was skipped.' }); continue; }
      if (entry.isDirectory()) await walk(absolute);
      else if (entry.isFile() && relative !== capabilityRelative) {
        const info = await regularUnder(root, relative).catch(() => null);
        if (!info || info.bytes > MAX_FILE_BYTES) { warnings.push({ source: relative, reason: 'Capability asset was skipped because it is unsafe or exceeds the file-size limit.' }); continue; }
        let text; try { text = utf8(await readFile(info.absolute)); } catch { warnings.push({ source: relative, reason: 'Binary or invalid UTF-8 capability asset was skipped.' }); continue; }
        const blocked = denied(text, relative);
        if (blocked) { warnings.push({ source: relative, reason: blocked }); continue; }
        found.push({ path: relative, digest: digest(text), bytes: info.bytes, kind: /(?:^|\/)scripts?(?:\/|$)|\.(?:sh|js|mjs|cjs|py|rb|pl|ps1)$/i.test(relative) ? 'script' : /(?:^|\/)references?(?:\/|$)|\.(?:md|txt|json|ya?ml)$/i.test(relative) ? 'reference' : 'asset', selectable: true, reasons: ['Capability assets are inert; scripts require explicit restricted consent before export.'] });
      }
    }
  }
  await walk(base);
  return found;
}

export async function inventoryRuntimeSources({ runtime, runtimeRoot } = {}) {
  if (!['claude', 'codex'].includes(runtime)) throw new TypeError('runtime must be claude or codex');
  const root = await rootFor(runtimeRoot);
  const warnings = [];
  const candidates = [];
  const global = runtime === 'claude' ? 'CLAUDE.md' : 'AGENTS.md';
  try {
    const file = await regularUnder(root, global);
    if (file.bytes > MAX_FILE_BYTES) warnings.push({ source: global, reason: 'Global instructions exceed the file-size limit.' });
    else {
      let text; try { text = utf8(await readFile(file.absolute)); } catch { warnings.push({ source: global, reason: 'Global instructions are binary or invalid UTF-8.' }); text = null; }
      if (text !== null) candidates.push(...instructionCandidates(runtime, global, text));
    }
  } catch (error) { if (error.code !== 'ENOENT') warnings.push({ source: global, reason: `Global instructions were skipped: ${error.message}` }); }
  try {
    const personalFile = await regularUnder(root, 'human.md');
    if (personalFile.bytes > MAX_FILE_BYTES) warnings.push({ source: 'human.md', reason: 'Personal context exceeds the file-size limit.' });
    else {
      const text = utf8(await readFile(personalFile.absolute));
      candidates.push(...instructionCandidates(runtime, 'human.md', text, {
        kind: 'personal-context',
        sensitivity: 'personal',
        reason: 'Canonical personal context is available only by explicit selection.',
      }));
    }
  } catch (error) { if (error.code !== 'ENOENT') warnings.push({ source: 'human.md', reason: `Personal context was skipped: ${error.message}` }); }
  const skills = path.join(root, 'skills');
  try {
    for (const entry of (await readdir(skills, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.') || entry.isSymbolicLink() || !entry.isDirectory()) continue;
      const relative = `skills/${entry.name}/SKILL.md`;
      try {
        const file = await regularUnder(root, relative);
        if (file.bytes > MAX_FILE_BYTES) { warnings.push({ source: relative, reason: 'Capability exceeds the file-size limit.' }); continue; }
        const text = utf8(await readFile(file.absolute)); const blocked = denied(text, relative);
        const skillAssets = await assets(root, relative, warnings);
        candidates.push({ id: stableId(runtime, 'capability', relative), runtime, sourceType: 'capability', source: relative, digest: digest(text), bytes: file.bytes, suggestedKind: 'capability', suggestedSensitivity: skillAssets.some((asset) => asset.kind === 'script') ? 'restricted' : 'standard', selectable: !blocked, reasons: [blocked ?? 'A runtime-specific skill is offered as a model-neutral capability candidate.'], assets: skillAssets });
      } catch (error) { warnings.push({ source: relative, reason: `Capability was skipped: ${error.message}` }); }
    }
  } catch (error) { if (error.code !== 'ENOENT') warnings.push({ source: 'skills', reason: `Skills directory was skipped: ${error.message}` }); }
  candidates.sort((a, b) => a.source.localeCompare(b.source) || (a.lineSpan?.start ?? 0) - (b.lineSpan?.start ?? 0) || a.id.localeCompare(b.id));
  warnings.sort((a, b) => a.source.localeCompare(b.source) || a.reason.localeCompare(b.reason));
  return { candidates, warnings };
}

export async function readCandidate(candidate, { runtimeRoot } = {}) {
  if (!candidate || typeof candidate !== 'object' || typeof candidate.source !== 'string' || typeof candidate.digest !== 'string') throw new TypeError('candidate must be an inventory candidate');
  if (!candidate.selectable) throw new Error('candidate is not selectable');
  const root = await rootFor(runtimeRoot);
  const file = await regularUnder(root, candidate.source);
  if (file.bytes > MAX_FILE_BYTES) throw new Error('candidate exceeds the file-size limit');
  const text = utf8(await readFile(file.absolute));
  let content;
  if (candidate.sourceType === 'instruction-section') {
    const section = authoredSections(text).find((item) =>
      item.heading === candidate.heading &&
      item.startLine === candidate.lineSpan?.start &&
      item.endLine === candidate.lineSpan?.end);
    content = section?.text;
  } else {
    content = text;
  }
  if (typeof content !== 'string' || digest(content) !== candidate.digest) throw new Error('candidate changed after inventory');
  if (candidate.portableTransform === 'memory-protocol-v1') content = PORTABLE_MEMORY_PROTOCOL;
  if (candidate.portableTransform === 'dev-server-safety-v1') content = PORTABLE_DEV_SAFETY;
  if (denied(content, candidate.source, candidate.heading)) throw new Error('candidate is no longer safe to read');
  return content;
}
