import { createHash } from 'node:crypto';
import { lstat, readFile, readdir, realpath } from 'node:fs/promises';
import path from 'node:path';

const MAX_FILE_BYTES = 256 * 1024;
const DENIED_NAME = /(?:transcript|history|prompt|credential|token|secret|settings?|permission|allowlist|trust|mcp|plugin|cron)/i;
const SECRET = /(?:\b(?:api[_-]?key|access[_-]?token|authorization|password|secret|private[_-]?key|cookie)\b\s*[:=]|https?:\/\/[^\s/]+[^\s]*[?&](?:token|api[_-]?key|key|secret|signature|sig|password|credential)=)/i;
const HOME_PATH = /(?:^|[\s"'`(])(?:\/Users\/[^/\s]+|\/home\/[^/\s]+|[A-Za-z]:\\Users\\[^\\\s]+)/;
const GENERATED = /(?:generated by saddle|saddle-managed|saddle portable)/i;

const digest = (value) => createHash('sha256').update(value).digest('hex');
const stableId = (...parts) => `capture-${digest(parts.join('\0')).slice(0, 20)}`;
const slash = (value) => value.split(path.sep).join('/');

function advisory(text, heading = '') {
  const title = heading.toLowerCase();
  if (/(personal|human|health|family|location)/.test(title)) return { kind: 'personal-context', sensitivity: 'personal', reason: 'The section heading suggests personal context; this advisory classification requires explicit consent.' };
  if (/(model routing|subagents?|project|design|writing)/.test(title)) return { kind: 'project-standard', sensitivity: 'standard', reason: 'The section heading suggests a project-standard; this is an advisory classification.' };
  if (/(session|memory|context|compact|resume|checkpoint|handover)/.test(title)) return { kind: 'session-continuity', sensitivity: 'standard', reason: 'The section heading suggests session continuity; this is an advisory classification.' };
  if (/(server|dev safety|permission)/.test(title)) return { kind: 'operating-policy', sensitivity: 'standard', reason: 'The section heading suggests an operating policy; this is an advisory classification.' };
  const sample = text.toLowerCase();
  if (/(personal|human|health|family|location)/.test(sample)) return { kind: 'personal-context', sensitivity: 'personal', reason: 'Personal-context terms were detected; this advisory classification requires explicit consent.' };
  if (/(session|memory|\bclear\b|compact|resume|pre[- ]?context|post[- ]?context|checkpoint|handover)/.test(sample)) return { kind: 'session-continuity', sensitivity: 'standard', reason: 'Session-continuity terms were detected; this is an advisory classification.' };
  if (/(server|dev safety|permission)/.test(sample)) return { kind: 'operating-policy', sensitivity: 'standard', reason: 'Operating-policy terms were detected; this is an advisory classification.' };
  if (/(model routing|subagents?|project|design|writing)/.test(sample)) return { kind: 'project-standard', sensitivity: 'standard', reason: 'Project-standard terms were detected; this is an advisory classification.' };
  return { kind: 'operating-policy', sensitivity: 'standard', reason: 'No stronger heuristic matched; this is an advisory operating-policy classification.' };
}

function denied(text, relative) {
  if (GENERATED.test(text) || /(?:^|\/)saddle(?:[-_.]|\/|$)/i.test(relative)) return 'Generated Saddle material is not importable.';
  if (DENIED_NAME.test(relative) || DENIED_NAME.test(text)) return 'Runtime settings, history, credentials, trust, integration, or scheduled-task material is excluded.';
  if (SECRET.test(text)) return 'Likely secret-bearing content is excluded.';
  if (HOME_PATH.test(text)) return 'Machine-specific absolute home paths cannot safely travel.';
  return null;
}

function utf8(buffer) {
  const text = new TextDecoder('utf-8', { fatal: true }).decode(buffer);
  if (text.includes('\0')) throw new Error('binary content');
  return text;
}

async function rootFor(runtimeRoot) {
  if (typeof runtimeRoot !== 'string' || !path.isAbsolute(runtimeRoot)) throw new TypeError('runtimeRoot must be an absolute caller-supplied path');
  return realpath(runtimeRoot);
}

async function regularUnder(root, relative) {
  const normalized = path.posix.normalize(relative.replaceAll('\\', '/'));
  if (!normalized || normalized === '.' || normalized.startsWith('../') || path.isAbsolute(normalized)) throw new Error('unsafe relative path');
  let current = root;
  for (const part of normalized.split('/')) {
    current = path.join(current, part);
    const info = await lstat(current);
    if (info.isSymbolicLink()) throw new Error('symlink traversal is not allowed');
  }
  const info = await lstat(current);
  if (!info.isFile()) throw new Error('not a regular file');
  const resolved = await realpath(current);
  if (!resolved.startsWith(`${root}${path.sep}`)) throw new Error('path escapes runtime root');
  return { relative: normalized, absolute: resolved, bytes: info.size };
}

function sections(text) {
  const lines = text.split(/(?<=\n)/);
  const headings = [];
  let position = 0;
  for (let index = 0; index < lines.length; index += 1) {
    const match = /^##\s+(.+?)\s*#*\s*(?:\r?\n)?$/.exec(lines[index]);
    if (match) headings.push({ index, position, heading: match[1].trim() });
    position += Buffer.byteLength(lines[index]);
  }
  const chunks = [];
  const first = headings[0]?.index ?? lines.length;
  if (first > 0) chunks.push({ heading: undefined, startLine: 1, endLine: first, text: lines.slice(0, first).join('') });
  for (let i = 0; i < headings.length; i += 1) {
    const start = headings[i].index;
    const end = headings[i + 1]?.index ?? lines.length;
    chunks.push({ heading: headings[i].heading, startLine: start + 1, endLine: end, text: lines.slice(start, end).join('') });
  }
  return chunks.filter((chunk) => chunk.text.trim());
}

function instructionCandidates(runtime, relative, text) {
  return sections(text).map((section) => {
    const classification = advisory(section.text, section.heading);
    const reason = denied(section.text, relative);
    return { id: stableId(runtime, 'instruction-section', relative, section.heading ?? 'introduction'), runtime, sourceType: 'instruction-section', source: relative, ...(section.heading ? { heading: section.heading } : {}), lineSpan: { start: section.startLine, end: section.endLine }, digest: digest(section.text), bytes: Buffer.byteLength(section.text), suggestedKind: classification.kind, suggestedSensitivity: classification.sensitivity, selectable: !reason, reasons: reason ? [reason] : [classification.reason] };
  });
}

async function assets(root, capabilityRelative, warnings) {
  const base = path.join(root, path.dirname(capabilityRelative));
  const found = [];
  async function walk(directory) {
    for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.')) continue;
      const absolute = path.join(directory, entry.name);
      const relative = slash(path.relative(root, absolute));
      if (entry.isSymbolicLink()) { warnings.push({ source: relative, reason: 'Symlinked capability asset was skipped.' }); continue; }
      if (entry.isDirectory()) await walk(absolute);
      else if (entry.isFile() && relative !== capabilityRelative) {
        const info = await regularUnder(root, relative).catch(() => null);
        if (!info || info.bytes > MAX_FILE_BYTES) { warnings.push({ source: relative, reason: 'Capability asset was skipped because it is unsafe or exceeds the file-size limit.' }); continue; }
        let text; try { text = utf8(await readFile(info.absolute)); } catch { warnings.push({ source: relative, reason: 'Binary or invalid UTF-8 capability asset was skipped.' }); continue; }
        const blocked = denied(text, relative);
        if (blocked) { warnings.push({ source: relative, reason: blocked }); continue; }
        found.push({ path: relative, digest: digest(text), bytes: info.bytes, kind: /(?:^|\/)scripts?(?:\/|$)|\.(?:sh|js|mjs|cjs|py|rb|pl|ps1)$/i.test(relative) ? 'script' : /(?:^|\/)references?(?:\/|$)|\.(?:md|txt|json|ya?ml)$/i.test(relative) ? 'reference' : 'asset', selectable: true, reasons: ['Capability assets are inert; scripts require explicit restricted consent before export.'] });
      }
    }
  }
  await walk(base);
  return found;
}

export async function inventoryRuntimeSources({ runtime, runtimeRoot } = {}) {
  if (!['claude', 'codex'].includes(runtime)) throw new TypeError('runtime must be claude or codex');
  const root = await rootFor(runtimeRoot);
  const warnings = [];
  const candidates = [];
  const global = runtime === 'claude' ? 'CLAUDE.md' : 'AGENTS.md';
  try {
    const file = await regularUnder(root, global);
    if (file.bytes > MAX_FILE_BYTES) warnings.push({ source: global, reason: 'Global instructions exceed the file-size limit.' });
    else {
      let text; try { text = utf8(await readFile(file.absolute)); } catch { warnings.push({ source: global, reason: 'Global instructions are binary or invalid UTF-8.' }); text = null; }
      if (text !== null) candidates.push(...instructionCandidates(runtime, global, text));
    }
  } catch (error) { if (error.code !== 'ENOENT') warnings.push({ source: global, reason: `Global instructions were skipped: ${error.message}` }); }
  const skills = path.join(root, 'skills');
  try {
    for (const entry of (await readdir(skills, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.') || entry.isSymbolicLink() || !entry.isDirectory()) continue;
      const relative = `skills/${entry.name}/SKILL.md`;
      try {
        const file = await regularUnder(root, relative);
        if (file.bytes > MAX_FILE_BYTES) { warnings.push({ source: relative, reason: 'Capability exceeds the file-size limit.' }); continue; }
        const text = utf8(await readFile(file.absolute)); const blocked = denied(text, relative);
        const skillAssets = await assets(root, relative, warnings);
        candidates.push({ id: stableId(runtime, 'capability', relative), runtime, sourceType: 'capability', source: relative, digest: digest(text), bytes: file.bytes, suggestedKind: 'capability', suggestedSensitivity: skillAssets.some((asset) => asset.kind === 'script') ? 'restricted' : 'standard', selectable: !blocked, reasons: [blocked ?? 'A runtime-specific skill is offered as a model-neutral capability candidate.'], assets: skillAssets });
      } catch (error) { warnings.push({ source: relative, reason: `Capability was skipped: ${error.message}` }); }
    }
  } catch (error) { if (error.code !== 'ENOENT') warnings.push({ source: 'skills', reason: `Skills directory was skipped: ${error.message}` }); }
  candidates.sort((a, b) => a.source.localeCompare(b.source) || (a.lineSpan?.start ?? 0) - (b.lineSpan?.start ?? 0) || a.id.localeCompare(b.id));
  warnings.sort((a, b) => a.source.localeCompare(b.source) || a.reason.localeCompare(b.reason));
  return { candidates, warnings };
}

export async function readCandidate(candidate, { runtimeRoot } = {}) {
  if (!candidate || typeof candidate !== 'object' || typeof candidate.source !== 'string' || typeof candidate.digest !== 'string') throw new TypeError('candidate must be an inventory candidate');
  if (!candidate.selectable) throw new Error('candidate is not selectable');
  const root = await rootFor(runtimeRoot);
  const file = await regularUnder(root, candidate.source);
  if (file.bytes > MAX_FILE_BYTES) throw new Error('candidate exceeds the file-size limit');
  const text = utf8(await readFile(file.absolute));
  if (denied(text, candidate.source)) throw new Error('candidate is no longer safe to read');
  const content = candidate.sourceType === 'instruction-section' ? sections(text).find((section) => section.heading === candidate.heading && section.startLine === candidate.lineSpan?.start && section.endLine === candidate.lineSpan?.end)?.text : text;
  if (typeof content !== 'string' || digest(content) !== candidate.digest) throw new Error('candidate changed after inventory');
  return content;
}
