import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { assertImportConsents, createImportPlan } from '../../src/domain/index.js';
import { exportProfile, loadProfile } from '../../src/profile/index.js';

const digest = (text) => createHash('sha256').update(text).digest('hex');
const continuity = { id: 'continuity', kind: 'session-continuity', source: 'instructions/session-continuity.md', enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest('# Continuity\n') };
const lifecycle = Object.fromEntries([['session.start', 'session-start'], ['session.checkpoint', 'session-checkpoint'], ['context.before-reset', 'before-context-reset'], ['context.after-reset', 'after-context-reset'], ['session.end', 'session-end']].map(([event, procedure]) => [event, { module: 'continuity', procedure }]));
async function makeProfile({ source = 'instructions/operating.md', text = 'safe guidance', module = {} } = {}) { const root = await mkdtemp(path.join(tmpdir(), 'saddle-privacy-')); await mkdir(path.dirname(path.join(root, source)), { recursive: true }); await mkdir(path.dirname(path.join(root, continuity.source)), { recursive: true }); await writeFile(path.join(root, source), text); await writeFile(path.join(root, continuity.source), '# Continuity\n'); const item = { id: 'module', kind: 'operating-policy', source, enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest(text), ...module }; const manifest = { schemaVersion: '1.0', profile: { id: 'safe', name: 'Safe', version: '1.0.0', createdAt: '2026-08-09T00:00:00.000Z', updatedAt: '2026-08-09T00:00:00.000Z' }, modules: [item, continuity], lifecycle, routing: { strategy: 'minimum-cost-that-clears-gate', routes: [] }, portability: { personalContext: 'prompt', integrations: 'declarations-only', scripts: 'copy-inert', absolutePaths: 'alias-only' } }; await writeFile(path.join(root, 'saddle.profile.json'), JSON.stringify(manifest)); return root; }

test('requires explicit item-level consent for personal context at export', async () => { const root = await makeProfile({ source: 'instructions/personal-context.md', module: { id: 'personal', kind: 'personal-context', sensitivity: 'personal', consent: 'explicit' } }); const parent = await mkdtemp(path.join(tmpdir(), 'saddle-export-')); const out = path.join(parent, 'bundle'); await assert.rejects(exportProfile(root, out), /explicit consent/); await assert.rejects(readFile(path.join(out, 'saddle.profile.json'))); const result = await exportProfile(root, out, { consent: { personal: true } }); assert.deepEqual(result.modules, ['personal', 'continuity']); });
test('rejects likely credential, transcript, and runtime-setting filenames', async () => { for (const source of ['credentials.json', 'logs/transcript.md', 'runtime-settings.json']) { const root = await makeProfile({ source }); await assert.rejects(loadProfile(root), /unsafe or denied path/); } });
test('rejects secret-bearing content and URLs before export', async () => { for (const text of ['api_key=abc123', 'Use https://example.test/connect?token=abc', ['gh', 'p_', 'abcdefghijklmnopqrstuvwx'].join(''), ['github_', 'pat_', 'abcdefghijklmnopqrstuvwx'].join(''), ['s', 'k-', 'abcdefghijklmnopqrstuvwx'].join(''), ['A', 'KIA', '1234567890ABCDEF'].join(''), ['xo', 'xb-', '1234567890-', 'abcdefghijklmnop'].join(''), '-----BEGIN PRIVATE KEY-----']) { const root = await makeProfile({ text }); await assert.rejects(loadProfile(root), /secret-bearing content/); } });
test('rejects an absolute home path in module content', async () => { const root = await makeProfile({ text: 'Read /Users/emily/.codex/config.json before acting.' }); await assert.rejects(loadProfile(root), /machine-specific path/); });
test('export contains only selected validated sources, never unrelated projections', async () => { const root = await makeProfile(); await mkdir(path.join(root, '.codex'), { recursive: true }); await writeFile(path.join(root, '.codex/generated.md'), 'projection'); const out = path.join(await mkdtemp(path.join(tmpdir(), 'saddle-export-parent-')), 'bundle'); await exportProfile(root, out); assert.equal(await readFile(path.join(out, 'instructions/operating.md'), 'utf8'), 'safe guidance'); await assert.rejects(readFile(path.join(out, '.codex/generated.md'))); });
test('export refuses an existing directory instead of mixing with or overwriting it', async () => { const root = await makeProfile(); const out = await mkdtemp(path.join(tmpdir(), 'saddle-existing-export-')); await assert.rejects(exportProfile(root, out), /must not already exist/); });
test('destination import requires item-level consent and marks personal projections', async () => { const root = await makeProfile({ source: 'instructions/personal-context.md', module: { id: 'personal', kind: 'personal-context', sensitivity: 'personal', consent: 'explicit' } }); const targetRoot = await mkdtemp(path.join(tmpdir(), 'saddle-personal-import-')); const preview = await createImportPlan({ profileRoot: root, targetRoot, runtimes: ['claude'] }); assert.deepEqual(preview.requiredConsents, [{ id: 'personal', kind: 'personal-context', sensitivity: 'personal' }]); assert.equal(preview.plan.operations.find((item) => item.id === 'claude:global-instructions').risk, 'personal'); assert.throws(() => assertImportConsents(preview.requiredConsents), { code: 'CONSENT_REQUIRED' }); assert.doesNotThrow(() => assertImportConsents(preview.requiredConsents, { personal: true })); });
