import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { inventoryRuntimeSources, readCandidate } from '../../src/capture/index.js';

async function runtime(files = {}) {
  const root = await mkdtemp(path.join(tmpdir(), 'saddle-capture-'));
  for (const [name, content] of Object.entries(files)) { await mkdir(path.dirname(path.join(root, name)), { recursive: true }); await writeFile(path.join(root, name), content); }
  return root;
}

test('splits global instructions and classifies advisory sections', async () => {
  const root = await runtime({ 'CLAUDE.md': 'Intro policy.\n## Dev Server Safety\nCap servers.\n## Pre-context Resume\nSave notes before compact.\n## Human context\nFamily schedule.\n' });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root });
  assert.deepEqual(candidates.map((item) => [item.heading, item.suggestedKind, item.suggestedSensitivity]), [[undefined, 'operating-policy', 'standard'], ['Dev Server Safety', 'operating-policy', 'standard'], ['Pre-context Resume', 'session-continuity', 'standard'], ['Human context', 'personal-context', 'personal']]);
  assert.match(candidates[1].reasons[0], /advisory/);
});

test('heading intent wins over ambiguous body verbs', async () => {
  const root = await runtime({ 'AGENTS.md': '## Model routing\nUse the least costly tier that can clear the acceptance gate.\n' });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'codex', runtimeRoot: root });
  assert.equal(candidates[0].suggestedKind, 'project-standard');
  assert.match(candidates[0].reasons[0], /heading/);
});

test('inventories capability assets and marks scripts restricted', async () => {
  const root = await runtime({ 'skills/example/SKILL.md': '# Example\n', 'skills/example/references/guide.md': 'Guide\n', 'skills/example/scripts/check.sh': '#!/bin/sh\nexit 0\n' });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'codex', runtimeRoot: root });
  const skill = candidates[0];
  assert.equal(skill.sourceType, 'capability'); assert.equal(skill.suggestedSensitivity, 'restricted');
  assert.deepEqual(skill.assets.map((asset) => [asset.path, asset.kind]), [['skills/example/references/guide.md', 'reference'], ['skills/example/scripts/check.sh', 'script']]);
});

test('excludes generated, secret-bearing, transcript, settings, and absolute-home candidates', async () => {
  const root = await runtime({ 'AGENTS.md': '## Generated\nGenerated by Saddle\n## Secret\napi_key=abc\n## Home\nUse /Users/emily/private\n', 'skills/history/SKILL.md': '# History\n', 'skills/settings/SKILL.md': '# Settings\n' });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'codex', runtimeRoot: root });
  assert.equal(candidates.every((candidate) => !candidate.selectable), true);
  await assert.rejects(readCandidate(candidates[0], { runtimeRoot: root }), /not selectable/);
});

test('skips symlink escapes, binary and large content without writes', async () => {
  const root = await runtime({ 'CLAUDE.md': Buffer.from([0, 1, 2]), 'skills/a/SKILL.md': 'x', 'skills/a/large.txt': 'x'.repeat(256 * 1024 + 1) });
  const outside = path.join(tmpdir(), `capture-outside-${Date.now()}`); await writeFile(outside, 'outside'); await symlink(outside, path.join(root, 'skills/a/link.txt'));
  const before = await readFile(path.join(root, 'skills/a/SKILL.md'), 'utf8');
  const first = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root }); const second = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root });
  assert.deepEqual(first, second); assert.equal(await readFile(path.join(root, 'skills/a/SKILL.md'), 'utf8'), before);
  assert.ok(first.warnings.some((warning) => /binary|large|size/i.test(warning.reason)));
});

test('requires absolute roots and detects drift before returning exact content', async () => {
  await assert.rejects(inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: 'relative' }), /absolute/);
  const root = await runtime({ 'CLAUDE.md': '## Keep\nOriginal\n' }); const { candidates } = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root });
  assert.equal(await readCandidate(candidates[0], { runtimeRoot: root }), '## Keep\nOriginal\n');
  await writeFile(path.join(root, 'CLAUDE.md'), '## Keep\nChanged\n');
  await assert.rejects(readCandidate(candidates[0], { runtimeRoot: root }), /changed/);
});

test('does not offer sections inside an existing Saddle-managed block', async () => {
  const root = await runtime({
    'CLAUDE.md': `## User policy\nKeep this.\n<!-- saddle:managed:start adapter=claude -->\n# Saddle operating profile\n## projected-policy\nDo not capture this generated section.\n<!-- saddle:managed:end adapter=claude -->\n`,
  });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root });
  assert.equal(candidates.find((candidate) => candidate.heading === 'User policy').selectable, true);
  assert.equal(candidates.some((candidate) => candidate.heading === 'projected-policy' && candidate.selectable), false);
});

test('keeps authored policy prose about permissions selectable', async () => {
  const root = await runtime({
    'AGENTS.md': '## Permission safety\nDo not transfer permission allowlists or trust grants.\n',
  });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'codex', runtimeRoot: root });
  assert.equal(candidates[0].selectable, true);
  assert.equal(candidates[0].suggestedKind, 'operating-policy');
});

test('excludes structural MCP connection configuration in global instructions', async () => {
  const root = await runtime({
    'AGENTS.md': '## MCP connection\nmcpServers:\n  internal:\n    url: https://mcp.internal.example/v1\n    command: private-launcher\n',
  });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'codex', runtimeRoot: root });
  assert.equal(candidates[0].selectable, false);
  assert.match(candidates[0].reasons[0], /connection/);
});

test('offers canonical human context as personal and never pre-authorizes it', async () => {
  const root = await runtime({
    'CLAUDE.md': '## Operating policy\nKeep changes reversible.\n',
    'human.md': '## Working preferences\nPrefer concise progress updates.\n',
  });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root });
  const personal = candidates.find((candidate) => candidate.source === 'human.md');
  assert.equal(personal.suggestedKind, 'personal-context');
  assert.equal(personal.suggestedSensitivity, 'personal');
  assert.equal(personal.selectable, true);
  assert.match(personal.reasons[0], /explicit selection/);
});

test('replaces source-machine dev-safety references with a self-contained portable policy', async () => {
  const root = await runtime({
    'CLAUDE.md': '## Dev server safety\nCanonical spec: `~/.claude/memory/_scripts/dev-safety/SPEC.md`\nUse the local wrapper.\n',
  });
  const { candidates } = await inventoryRuntimeSources({ runtime: 'claude', runtimeRoot: root });
  assert.equal(candidates[0].selectable, true);
  assert.equal(candidates[0].portableTransform, 'dev-server-safety-v1');
  const content = await readCandidate(candidates[0], { runtimeRoot: root });
  assert.match(content, /complete process tree/);
  assert.match(content, /2048 MB/);
  assert.doesNotMatch(content, /~\/\.claude/);
});
