import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { exportProfile, inventoryProfile, loadProfile, normalizePortablePath, ProfileError, validateManifest } from '../../src/profile/index.js';

const digest = (text) => createHash('sha256').update(text).digest('hex');
const continuity = { id: 'continuity', kind: 'session-continuity', source: 'instructions/session-continuity.md', enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest('# Continuity\n') };
const lifecycle = Object.fromEntries([['session.start', 'session-start'], ['session.checkpoint', 'session-checkpoint'], ['context.before-reset', 'before-context-reset'], ['context.after-reset', 'after-context-reset'], ['session.end', 'session-end']].map(([event, procedure]) => [event, { module: 'continuity', procedure }]));
const portableState = { lifecycle, routing: { strategy: 'minimum-cost-that-clears-gate', routes: [] }, portability: { personalContext: 'prompt', integrations: 'declarations-only', scripts: 'copy-inert', absolutePaths: 'alias-only' } };
const manifestFor = (source, text, override = {}) => ({ schemaVersion: '1.0', profile: { id: 'universal', name: 'Universal profile', version: '1.0.0', createdAt: '2026-08-09T00:00:00.000Z', updatedAt: '2026-08-09T00:00:00.000Z' }, modules: [{ id: 'operating', kind: 'operating-policy', source, enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest(text) }, continuity], ...portableState, ...override });
async function profile(source = 'instructions/operating.md', text = '# Operate safely\n', override = {}) { const root = await mkdtemp(path.join(tmpdir(), 'saddle-profile-')); await mkdir(path.dirname(path.join(root, source)), { recursive: true }); await writeFile(path.join(root, source), text); await writeFile(path.join(root, continuity.source), '# Continuity\n'); await writeFile(path.join(root, 'saddle.profile.json'), JSON.stringify(manifestFor(source, text, override))); return root; }

test('loads a valid universal profile with a verified digest', async () => { const root = await profile(); const loaded = await loadProfile(root); assert.equal(loaded.manifest.profile.id, 'universal'); assert.equal(loaded.modules.length, 2); });
test('rejects unknown manifest fields', () => assert.throws(() => validateManifest({ ...manifestFor('a.md', 'x'), surprise: true }), ProfileError));
test('rejects digest mismatch', async () => { const root = await profile(); await writeFile(path.join(root, 'instructions/operating.md'), 'changed'); await assert.rejects(loadProfile(root), /digest mismatch/); });
test('normalizes only a uniquely approved absolute path to an alias', () => { assert.equal(normalizePortablePath('/tmp/home/projects/a', { home: '/tmp/home', workspace: '/tmp/work' }), '${home}/projects/a'); assert.throws(() => normalizePortablePath('/outside/a', { home: '/tmp/home' }), /no approved alias/); assert.throws(() => normalizePortablePath('/tmp/home/a', { home: '/tmp/home', workspace: '/tmp/home' }), /ambiguous/); });
test('rejects absolute source paths and traversal', () => { assert.throws(() => validateManifest(manifestFor('/Users/example/private.md', 'x')), /resolved relative/); assert.throws(() => validateManifest(manifestFor('../private.md', 'x')), /unsafe/); });
test('rejects a source reached through a symlink', async () => { const root = await mkdtemp(path.join(tmpdir(), 'saddle-profile-')); const outside = path.join(tmpdir(), `outside-${Date.now()}.md`); await writeFile(outside, 'outside'); await mkdir(path.join(root, 'instructions')); await symlink(outside, path.join(root, 'instructions/operating.md')); await writeFile(path.join(root, 'saddle.profile.json'), JSON.stringify(manifestFor('instructions/operating.md', 'outside'))); await assert.rejects(loadProfile(root), /symlink traversal/); });

async function capabilityProfile({ assetPath = 'capabilities/portable/references/guide.md', assetContent = 'reference', module = {} } = {}) {
  const root = await mkdtemp(path.join(tmpdir(), 'saddle-capability-')); const source = 'capabilities/portable/CAPABILITY.md'; const sourceContent = '# Portable\n';
  await mkdir(path.dirname(path.join(root, source)), { recursive: true }); await mkdir(path.dirname(path.join(root, assetPath)), { recursive: true }); await mkdir(path.dirname(path.join(root, continuity.source)), { recursive: true }); await writeFile(path.join(root, source), sourceContent); await writeFile(path.join(root, assetPath), assetContent); await writeFile(path.join(root, continuity.source), '# Continuity\n');
  const descriptor = { id: 'portable', kind: 'capability', source, enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest(sourceContent), assets: [{ path: assetPath, digest: digest(assetContent), kind: 'reference' }], ...module };
  const manifest = manifestFor(source, sourceContent, { modules: [descriptor, continuity] }); await writeFile(path.join(root, 'saddle.profile.json'), JSON.stringify(manifest)); return root;
}
test('loads inert capability reference assets with stable adapter metadata and exports them', async () => { const root = await capabilityProfile(); const loaded = await loadProfile(root); const capability = loaded.modules.find((module) => module.id === 'portable'); assert.deepEqual(capability.assets.map(({ path, digest, kind }) => ({ path, digest, kind })), [{ path: 'capabilities/portable/references/guide.md', digest: digest('reference'), kind: 'reference' }]); const inventory = await inventoryProfile(root); assert.deepEqual(inventory.find((module) => module.id === 'portable').assets, [{ path: 'capabilities/portable/references/guide.md', digest: digest('reference'), kind: 'reference' }]); const out = path.join(await mkdtemp(path.join(tmpdir(), 'saddle-cap-export-')), 'bundle'); await exportProfile(root, out); assert.equal(await readFile(path.join(out, 'capabilities/portable/references/guide.md'), 'utf8'), 'reference'); });
test('accepts and exports a restricted, explicitly consented script as inert content', async () => { const root = await capabilityProfile({ assetPath: 'capabilities/portable/scripts/check.js', assetContent: 'throw new Error(\"not executed\")', module: { sensitivity: 'restricted', consent: 'explicit', assets: [{ path: 'capabilities/portable/scripts/check.js', digest: digest('throw new Error(\"not executed\")'), kind: 'script' }] } }); const out = path.join(await mkdtemp(path.join(tmpdir(), 'saddle-script-export-')), 'bundle'); await assert.rejects(exportProfile(root, out), /explicit consent/); await exportProfile(root, out, { consent: { portable: true } }); assert.equal(await readFile(path.join(out, 'capabilities/portable/scripts/check.js'), 'utf8'), 'throw new Error("not executed")'); });
test('rejects invalid capability asset path, symlink, digest, and script consent', async () => { const outside = 'outside.md'; const badPath = await capabilityProfile({ assetPath: outside, module: { assets: [{ path: outside, digest: digest('reference'), kind: 'reference' }] } }); await assert.rejects(loadProfile(badPath), /beneath capability directory/); const mismatch = await capabilityProfile({ module: { assets: [{ path: 'capabilities/portable/references/guide.md', digest: digest('wrong'), kind: 'reference' }] } }); await assert.rejects(loadProfile(mismatch), /asset digest mismatch/); const script = await capabilityProfile({ module: { assets: [{ path: 'capabilities/portable/references/guide.md', digest: digest('reference'), kind: 'script' }] } }); await assert.rejects(loadProfile(script), /script assets require restricted/); const linked = await capabilityProfile(); const target = path.join(tmpdir(), `asset-outside-${Date.now()}.md`); await writeFile(target, 'reference'); await writeFile(path.join(linked, 'capabilities/portable/references/guide.md'), 'temporary'); await symlink(target, path.join(linked, 'capabilities/portable/references/link.md')); const manifest = JSON.parse(await readFile(path.join(linked, 'saddle.profile.json'), 'utf8')); manifest.modules[0].assets = [{ path: 'capabilities/portable/references/link.md', digest: digest('reference'), kind: 'reference' }]; await writeFile(path.join(linked, 'saddle.profile.json'), JSON.stringify(manifest)); await assert.rejects(loadProfile(linked), /symlink traversal/); });
test('rejects duplicate asset paths, source duplication, and assets on non-capability modules', () => { const duplicate = manifestFor('capabilities/a/CAPABILITY.md', 'x', { modules: [{ id: 'a', kind: 'capability', source: 'capabilities/a/CAPABILITY.md', enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest('x'), assets: [{ path: 'capabilities/a/references/x.md', digest: digest('x'), kind: 'reference' }, { path: 'capabilities/a/references/x.md', digest: digest('x'), kind: 'reference' }] }] }); assert.throws(() => validateManifest(duplicate), /duplicate asset path/); const sourceDuplicate = manifestFor('capabilities/a/CAPABILITY.md', 'x', { modules: [{ id: 'a', kind: 'capability', source: 'capabilities/a/CAPABILITY.md', enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest('x'), assets: [{ path: 'capabilities/a/references/x.md', digest: digest('x'), kind: 'reference' }] }, { id: 'b', kind: 'operating-policy', source: 'capabilities/a/references/x.md', enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest('x') }] }); assert.throws(() => validateManifest(sourceDuplicate), /duplicate module source/); const nonCapability = manifestFor('instructions/a.md', 'x', { modules: [{ id: 'a', kind: 'operating-policy', source: 'instructions/a.md', enabled: true, sensitivity: 'standard', consent: 'implicit', digest: digest('x'), assets: [{ path: 'instructions/x.md', digest: digest('x'), kind: 'reference' }] }] }); assert.throws(() => validateManifest(nonCapability), /only capability/); });
test('rejects environment-file capability assets', async () => { const root = await capabilityProfile({ assetPath: 'capabilities/portable/.env', assetContent: 'INTERNAL_HOST=private.corp', module: { assets: [{ path: 'capabilities/portable/.env', digest: digest('INTERNAL_HOST=private.corp'), kind: 'reference' }] } }); await assert.rejects(loadProfile(root), /unsafe or denied path/); });
test('requires strict lifecycle, routing, and portability contracts', () => { const missing = manifestFor('a.md', 'x', { lifecycle: {} }); assert.throws(() => validateManifest(missing), /missing required event/); const dangling = manifestFor('a.md', 'x', { lifecycle: { ...lifecycle, 'session.start': { module: 'missing', procedure: 'session-start' } } }); assert.throws(() => validateManifest(dangling), /enabled session-continuity/); const wrongKind = manifestFor('a.md', 'x', { lifecycle: { ...lifecycle, 'session.start': { module: 'operating', procedure: 'session-start' } } }); assert.throws(() => validateManifest(wrongKind), /enabled session-continuity/); const unknown = manifestFor('a.md', 'x', { lifecycle: { ...lifecycle, 'runtime.start': { module: 'continuity', procedure: 'session-start' } } }); assert.throws(() => validateManifest(unknown), /unknown field/); const validRoute = manifestFor('a.md', 'x', { routing: { strategy: 'minimum-cost-that-clears-gate', routes: [{ id: 'analysis', taskKinds: ['research'], capabilityLevel: 'high', reasoningLevel: 'medium', escalationCondition: 'Use frontier capability when source evidence conflicts.' }] } }); assert.doesNotThrow(() => validateManifest(validRoute)); const concrete = manifestFor('a.md', 'x', { routing: { strategy: 'minimum-cost-that-clears-gate', routes: [{ id: 'analysis', taskKinds: ['research'], capabilityLevel: 'high', reasoningLevel: 'medium', escalationCondition: 'Escalate.', model: 'gpt-5' }] } }); assert.throws(() => validateManifest(concrete), /unknown field/); });
